---
# 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)

- name: 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
  systemd:
    name: squid
    state: stopped
    enabled: no
  when: cis_squid_server == false and squid_service_status.stdout == "loaded"
  tags:
    - level1
    - section02
    - section02_level1
    - scored
    - "2.2.13"
