---
# 2.2.1.2 Ensure ntp is configured (Scored)

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  template:
      src: etc/ntp.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
  notify: restart ntpd
  when: cis_enable_ntp
  tags:
      - level1
      - section01
      - section01_level1
      - scored
      - "2.2.1.2"

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  lineinfile:
      dest: /etc/sysconfig/ntpd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u ntp:ntp\""
  when: cis_enable_ntp
  notify: restart ntpd
  tags:
    - level1
    - section01
    - section01_level1
    - scored
    - "2.2.1.2"
