---
# 2.2.1.3 Ensure chrony is configured (Scored)

- name: 2.2.1.3 Ensure chrony is configured (Scored)
  template:
      src: etc/chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
  notify: restart chronyd
  when: cis_enable_chrony
  tags:
      - level1
      - section01
      - section01_level1
      - scored
      - "2.2.1.3"

- name: 2.2.1.3 Ensure chrony is configured (Scored)
  lineinfile:
      dest: /etc/sysconfig/chronyd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u chrony\""
      state: present
      create: yes
  when: cis_enable_chrony
  notify: restart chronyd
  tags:
    - level1
    - section01
    - section01_level1
    - scored
    - "2.2.1.3"
