---
# 2.2.9 Ensure FTP Server is not enabled (Scored)

- name: 2.2.9 Ensure FTP Server is not enabled (Scored)
  systemd:
    name: vsftpd
    state: stopped
    enabled: no
  when: cis_ftp_server == false and vsftpd_service_status.stdout == "loaded"
  tags:
    - level1
    - section02
    - section02_level1
    - scored
    - "2.2.9"
