---
# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
# 1.1.4 Ensure nosuid option set on /tmp partition (Scored) [NOT Separated Partition]
# 1.1.5 Ensure noexec option set on /tmp partition (Scored) [NOT Separated Partition]

- name: 1.1.3 - Ensure nodev option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  register: tmp_mounted
  tags:
    - level1
    - section01
    - section01_level1
    - "1.1.3"
    - scored

- name: 1.1.3 - Check if systemd tmp.mount unit-file exists
  stat:
    path: /etc/systemd/system/local-fs.target.wants/tmp.mount
  register: unitfile
  when: not tmp_mounted.changed
  tags:
    - level1
    - section01_level1
    - section01
    - "1.1.3"
    - scored

- name: "1.1.3 - Ensure nodev option set on /tmp partition\n
         1.1.4 - 1.1.4 Ensure nosuid option set on /tmp partition (Scored)\n
         1.1.5 Ensure noexec option set on /tmp partition (Scored)"
  lineinfile:
    dest: /etc/systemd/system/local-fs.target.wants/tmp.mount
    regexp: "^Options="
    insertafter: "^Type="
    line: "Options=mode=1777,strictatime,noexec,nodev,nosuid"
  when: unitfile.stat.exists and not tmp_mounted.changed
  tags:
    - level1
    - section01_level1
    - section01
    - "1.1.3"
    - scored
  notify: restart tmp.mount

