---
# 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)

- name: 1.1.1.3 - Check if CIS modprobe configuration exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_3
  tags:
    - level1
    - section01
    - "1.1.1.3"
    - scored

- name: 1.1.1.3 - Check if jffs2 is disabled
  command: modprobe -n -v jffs2
  register: mod_jffs2
  changed_when: mod_jffs2.stdout | search('jffs2')
  check_mode: false
  failed_when: mod_jffs2.rc not in (0,1)
  tags:
    - level1
    - section01
    - "1.1.1.3"
    - scored

- name: 1.1.1.3 - Check if jffs2 is loaded
  command: lsmod
  check_mode: false
  register: lsmod
  tags:
    - level1
    - section01
    - "1.1.1.3"
    - scored
  changed_when: lsmod.stdout | search('jffs2')

- name: 1.1.1.3 - Unload jffs2 if required
  command: modprobe -r jffs2
  register: mod_jffs2_remove
  changed_when: mod_jffs2_remove.rc == 0
  when: lsmod.stdout | search('jffs2.*')
  tags:
    - level1
    - section01
    - "1.1.1.3"
    - scored

- name: 1.1.1.3 - Ensure mounting of jffs2 filesystems is disabled
  lineinfile: 
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install jffs2" 
    line: "install jffs2 /bin/true" 
  when: modprobe_1_1_1_3.stat.exists is defined and modprobe_1_1_1_3.stat.exists
  tags:
    - level1
    - section01
    - "1.1.1.3"
    - scored
