---
# 1.4.3 Ensure authentication required for single user mode (Not Scored)

- name: 1.4.3 Ensure authentication required for single user mode (Not Scored)
  replace:
    name: "{{ item }}"
    regexp: "^ExecStart=.*"
    replace: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  with_items:
    - /usr/lib/systemd/system/rescue.service
    - /usr/lib/systemd/system/emergency.service
  tags:
    - section01
    - level1
    - section01_level1
    - "1.4.3"

