---
# 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)

- name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
  lineinfile:
     dest: /etc/audit/auditd.conf
     regexp: "^admin_space_left"
     line: "admin_space_left_action = halt"
     state: present
  tags:
     - section4
     - level2
     - section4_level2
     - "4.1.1.2"
     - "scored"
