---
# 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)

- name: 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
  lineinfile:
     dest: /etc/audit/auditd.conf
     regexp: "^max_log_file_action"
     line: "max_log_file_action = keep_logs"
     state: present
  tags:
     - section4
     - level2
     - section4_level2
     - "4.1.1.3"
     - "scored"
